import "./globals.css";
import { Poppins } from 'next/font/google'

const poppins = Poppins ({
  weight: ['200', '400', '500', '600', '700', '800'],
  subsets: ['latin'],
  variable: "--font-poppins"
})

export const metadata = {
  title: "Sabor Solidário",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-Br">
      <body>{children}</body>
    </html>
  );
}
